create table if not exists posts (
    id bigint generated by default as identity primary key,
    date text not null,
    platform text not null,
    title text not null,
    pillar text not null,
    format text not null,
    weekday text not null,
    hour integer not null,
    reach integer not null,
    likes integer not null,
    comments integer not null,
    quality_comments integer not null,
    shares integer not null,
    saves integer not null,
    profile_visits integer not null,
    website_clicks integer not null,
    engagement_rate double precision not null,
    share_rate double precision not null,
    save_rate double precision not null,
    quality_comment_rate double precision not null,
    profile_visit_rate double precision not null
);

create table if not exists daily_metrics (
    date text primary key,
    reach integer not null,
    profile_visits integer not null,
    website_clicks integer not null,
    followers_delta integer not null
);

create table if not exists profile_metrics (
    id bigint generated by default as identity primary key,
    date text not null,
    platform text not null,
    followers integer not null,
    profile_visits integer not null,
    website_clicks integer not null,
    dm_leads integer not null,
    profile_visit_rate double precision not null
);

create table if not exists monetization_signals (
    id bigint generated by default as identity primary key,
    date text not null,
    source text not null,
    workshop_leads integer not null,
    consulting_leads integer not null,
    collab_leads integer not null,
    estimated_value_usd integer not null
);

create table if not exists content_ideas (
    id bigint generated by default as identity primary key,
    pillar text not null,
    format text not null,
    title text not null,
    hook text not null,
    share_save_mechanism text not null,
    cta text not null,
    strategic_reason text not null,
    priority text not null,
    linkedin_adaptation text not null,
    created_at timestamptz default now()
);

create table if not exists screenshots (
    id bigint generated by default as identity primary key,
    date text not null,
    platform text not null,
    content_title text not null,
    image_path text not null,
    notes text,
    ai_reading text,
    created_at timestamptz default now()
);

create table if not exists inspirations (
    id bigint generated by default as identity primary key,
    url text not null,
    title text,
    source_notes text,
    domo_angle text,
    suggested_content text,
    created_at timestamptz default now()
);

create table if not exists assistant_notes (
    id bigint generated by default as identity primary key,
    question text not null,
    answer text not null,
    created_at timestamptz default now()
);

create table if not exists trend_items (
    id bigint generated by default as identity primary key,
    query text not null,
    title text not null,
    url text not null,
    source text,
    domo_reading text,
    created_at timestamptz default now()
);

create table if not exists collab_targets (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null,
    why_fit text not null,
    approach text not null,
    priority text not null,
    status text default 'Por investigar',
    url text,
    created_at timestamptz default now()
);

create table if not exists action_items (
    id bigint generated by default as identity primary key,
    title text not null,
    area text not null,
    reason text not null,
    priority text not null,
    status text default 'Pendiente',
    created_at timestamptz default now()
);

create table if not exists carousel_drafts (
    id bigint generated by default as identity primary key,
    source text not null,
    title text not null,
    objective text not null,
    slides_json text not null,
    caption text,
    cta text,
    created_at timestamptz default now()
);

create index if not exists posts_date_idx on posts (date desc);
create index if not exists posts_platform_idx on posts (platform);
create index if not exists carousel_drafts_created_at_idx on carousel_drafts (created_at desc);
create index if not exists inspirations_created_at_idx on inspirations (created_at desc);
create index if not exists assistant_notes_created_at_idx on assistant_notes (created_at desc);
